### ISSUE TITLE
How to encode txt file

### ISSUE THREAD

**Issue by Emirhantaze** [CommitteeOfZero/SciAdv.Net#3]

**Comment by Emirhantaze** [comment]
I can get all txt script files of SG zero but i don't know How to repack them again to translate it
.

**Comment by ModzabazeR** [comment]
Can you fix the problem yet?

**Comment by sa-exe** [comment]
SciAdv.Net is no longer maintained. Take a look at [sc3tools 2.0](https://github.com/CommitteeOfZero/sc3tools).
